version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password  # Corrected the typo here
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
